# Generated by Django 4.0a1 on 2021-10-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productiver',
        ),
    ]
