# Generated by Django 3.2.6 on 2021-08-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='title',
        ),
        migrations.AddField(
            model_name='todolist',
            name='task_description',
            field=models.TextField(default='Description', max_length=200),
        ),
        migrations.AddField(
            model_name='todolist',
            name='task_title',
            field=models.CharField(default='Task Title', max_length=50),
        ),
    ]
