# Generated by Django 4.0a1 on 2021-10-30 11:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0005_alter_todolist_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='priority',
            field=models.PositiveBigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='productiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_author', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='task_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
