# Generated by Django 4.0a1 on 2021-10-30 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0007_alter_todolist_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='productiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='auth.user'),
        ),
    ]
